import { Application } from "./types";

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: "demo-1",
    company: "OpenAI",
    role: "Research Science Intern",
    location: "San Francisco, CA",
    status: "Interview",
    dateApplied: "2026-08-01",
    salary: "$65/hr ($11,260/mo)",
    priority: "Urgent",
    contactName: "Dr. Sarah Lin (Recruiter)",
    contactEmail: "slin@openai.com",
    deadline: "2026-08-25",
    link: "https://openai.com/careers",
    notes: "Passed Technical Screening. Final round 3x45min coding & system design scheduled for next week!",
    createdAt: Date.now() - 15 * 86400000,
  },
  {
    id: "demo-2",
    company: "Anthropic",
    role: "AI Safety Systems Intern",
    location: "San Francisco, CA / Remote",
    status: "Offer",
    dateApplied: "2026-07-20",
    salary: "$70/hr + $3,000 Housing",
    priority: "Urgent",
    contactName: "Alex Vance",
    contactEmail: "alex@anthropic.com",
    deadline: "2026-08-30",
    link: "https://anthropic.com/careers",
    notes: "🎉 OFFICIAL OFFER RECEIVED! $70/hr with housing stipend. Need to respond before August 30th.",
    createdAt: Date.now() - 25 * 86400000,
  },
  {
    id: "demo-3",
    company: "Tesla",
    role: "Autopilot AI Engineering Intern",
    location: "Palo Alto, CA",
    status: "Online Assessment",
    dateApplied: "2026-08-05",
    salary: "$55/hr",
    priority: "High",
    contactName: "Tesla University Relations",
    contactEmail: "interns@tesla.com",
    deadline: "2026-08-20",
    link: "https://tesla.com/careers",
    notes: "OA received on HackerRank: 3 algorithmic questions. Need to submit by Friday.",
    createdAt: Date.now() - 10 * 86400000,
  },
  {
    id: "demo-4",
    company: "Stripe",
    role: "Backend Infrastructure Intern",
    location: "Seattle, WA / Remote",
    status: "Applied",
    dateApplied: "2026-08-10",
    salary: "$62/hr",
    priority: "High",
    contactName: "Marcus Brody",
    contactEmail: "mbrody@stripe.com",
    deadline: "2026-09-01",
    link: "https://stripe.com/jobs",
    notes: "Applied via internal referral from college alumni. Awaiting confirmation.",
    createdAt: Date.now() - 5 * 86400000,
  },
  {
    id: "demo-5",
    company: "Google",
    role: "STEP / Software Engineering Intern",
    location: "Mountain View, CA",
    status: "Interview",
    dateApplied: "2026-07-15",
    salary: "$58/hr + Relocation",
    priority: "Medium",
    contactName: "Google University Team",
    contactEmail: "step-recruiting@google.com",
    deadline: "2026-08-28",
    link: "https://careers.google.com",
    notes: "Host matching phase in progress! Spoke with Chrome Team and Cloud AI Team.",
    createdAt: Date.now() - 30 * 86400000,
  },
  {
    id: "demo-6",
    company: "Apple",
    role: "Core OS & Machine Learning Intern",
    location: "Cupertino, CA",
    status: "Wishlist",
    dateApplied: "",
    salary: "$60/hr",
    priority: "Medium",
    contactName: "",
    contactEmail: "",
    deadline: "2026-09-15",
    link: "https://apple.com/jobs",
    notes: "Need to polish C++ and Metal framework projects before submitting application.",
    createdAt: Date.now() - 2 * 86400000,
  },
];
